# import libraries
from pyspark.sql import SparkSession
from pyspark.conf import SparkConf
from pyspark.sql import HiveContext
from pyspark.sql.functions import *
from pyspark.sql.types import *

# init sparkConf
conf = SparkConf()
conf.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer") \
    .set("spark.executor.cores", "8") \
    .set("spark.executor.memory", "8G") \
    .set("spark.sql.cbo.enabled", "true")

# Initialize Spark Session
spark = SparkSession.builder.appName("flat_structure").config(conf=SparkConf()).enableHiveSupport().getOrCreate()

# Initialize Spark Context
sc = spark.sparkContext

# Initialize Hive Context (allow us to query immediately table through HQL-Hive Query Language)
sqlContext = HiveContext(sc)

# Defining database used
sqlContext.sql("use kylin_usb_mqb")

tableFinale = sqlContext.sql("""
SELECT DISTINCT
      EG.ELG_NUM_ELT_GESTION_ELG AS ELG_NUM_ELT_GESTION_ELG
     ,CF1.COF_CODE_FOURNISSEUR AS FST_ARTICLE_R3
     ,EG.ELG_NUM_ELT_GESTION_MOD AS ELG_NUM_ELT_GESTION_MOD
     ,CF2.COF_CODE_FOURNISSEUR AS FST_MODELE_R3
     ,RM.ORG_NUM_ORGANISATION_ELN AS ORG_NUM_ORGANISATION_ORG
     ,ELNFAM.NIV_NUM_NIVEAU_NIV AS NIV_NUM_NIVEAU_FAM
     ,ELNFAM.ELN_NUM_ELT_NIVEAU AS ELN_NUM_ELT_NIVEAU_FAM
     ,ELNSSR.NIV_NUM_NIVEAU_NIV AS NIV_NUM_NIVEAU_SSR
     ,ELNSSR.ELN_NUM_ELT_NIVEAU AS ELN_NUM_ELT_NIVEAU_SSR
     ,ELNRAY.NIV_NUM_NIVEAU_NIV AS NIV_NUM_NIVEAU_RAY
     ,ELNRAY.ELN_NUM_ELT_NIVEAU AS ELN_NUM_ELT_NIVEAU_RAY
     ,ELNUNI.NIV_NUM_NIVEAU_NIV AS NIV_NUM_NIVEAU_UNI
     ,ELNUNI.ELN_NUM_ELT_NIVEAU AS ELN_NUM_ELT_NIVEAU_UNI
     ,ELNMAG.NIV_NUM_NIVEAU_NIV AS NIV_NUM_NIVEAU_MAG
     ,ELNMAG.ELN_NUM_ELT_NIVEAU AS ELN_NUM_ELT_NIVEAU_MAG
     ,LM.TLB_TYP_LIBELLE_LIB AS FST_TYP_LIB_MODELE
     ,LM.LIB_NUM_LIBELLE_LIB AS FST_NUM_LIB_MODELE
     ,VG.TLB_TYP_LIBELLE_LIB AS FST_TYP_LIB_VAL_GRILLE
     ,VG.LIB_NUM_LIBELLE_LIB AS FST_NUM_LIB_VAL_GRILLE
     ,ELNFAM.TLB_TYP_LIBELLE_LIB AS FST_TYP_LIB_NIV_FAM
     ,ELNFAM.LIB_NUM_LIBELLE_LIB AS FST_NUM_LIB_NIV_FAM
     ,ELNSSR.TLB_TYP_LIBELLE_LIB AS FST_TYP_LIB_NIV_SSR
     ,ELNSSR.LIB_NUM_LIBELLE_LIB AS FST_NUM_LIB_NIV_SSR
     ,ELNRAY.TLB_TYP_LIBELLE_LIB AS FST_TYP_LIB_NIV_RAY
     ,ELNRAY.LIB_NUM_LIBELLE_LIB AS FST_NUM_LIB_NIV_RAY
     ,ELNUNI.TLB_TYP_LIBELLE_LIB AS FST_TYP_LIB_NIV_UNI
     ,ELNUNI.LIB_NUM_LIBELLE_LIB AS FST_NUM_LIB_NIV_UNI
     ,ELNMAG.TLB_TYP_LIBELLE_LIB AS FST_TYP_LIB_NIV_MAG
     ,ELNMAG.LIB_NUM_LIBELLE_LIB AS FST_NUM_LIB_NIV_MAG
     ,mlt1.lit_libelle_long as LIBELLE_MODELE
     ,mlt2.lit_libelle_long as LIBELLE_FAMILLE
     ,mlt3.lit_libelle_long as LIBELLE_SOUS_RAYON
     ,mlt4.lit_libelle_long as LIBELLE_RAYON
     ,mlt5.lit_libelle_long as LIBELLE_UNIVERS
FROM
  MDS_ELEMENT_GESTION EG
---------------------------------------------------------------------------
LEFT OUTER JOIN
  MDS_CODIFICATION_FOURNISSEUR CF1
ON
    CF1.ELG_NUM_ELT_GESTION_ELG = EG.ELG_NUM_ELT_GESTION_ELG
AND CF1.TTI_NUM_TYPE_TIERS_FOUR = 46
AND CF1.TIR_NUM_TIERS_FOUR = 1
AND CF1.TIR_SOUS_NUM_TIERS_FOUR = 1
---------------------------------------------------------------------------
LEFT OUTER JOIN
  MDS_CODIFICATION_FOURNISSEUR CF2
ON
    CF2.ELG_NUM_ELT_GESTION_ELG = EG.ELG_NUM_ELT_GESTION_MOD
AND CF2.TTI_NUM_TYPE_TIERS_FOUR = 46
AND CF2.TIR_NUM_TIERS_FOUR = 1
AND CF2.TIR_SOUS_NUM_TIERS_FOUR = 1
---------------------------------------------------------------------------
LEFT OUTER JOIN
  MDS_LIBELLE_MODELE LM
ON
    LM.ELG_NUM_ELT_GESTION_ELG = EG.ELG_NUM_ELT_GESTION_MOD
AND LM.TLB_TYP_LIBELLE_LIB = 'LMO'
---------------------------------------------------------------------------
LEFT OUTER JOIN (
  SELECT
      DAS3.ELG_NUM_ELT_GESTION_ELG
      ,DAS3.VAL_GRILLE_VAG
      ,DAS3.TGR_NUM_TYPE_GRILLE_VAG
      ,DAS3.TTI_NUM_TYPE_TIERS_VAG
      ,DAS3.TIR_NUM_TIERS_VAG
      ,DAS3.TIR_SOUS_NUM_TIERS_VAG
      ,DAS3.DEC_DATE_CREATION
      ,DAS3.DEC_DATE_MAJ
      ,DAS3.DEC_DATE_MAJ_TEC
  FROM
      (
      SELECT
       DAS.elg_num_elt_gestion_elg
      ,DAS.VAL_GRILLE_VAG
      ,DAS.TGR_NUM_TYPE_GRILLE_VAG
      ,DAS.TTI_NUM_TYPE_TIERS_VAG
      ,DAS.TIR_NUM_TIERS_VAG
      ,DAS.TIR_SOUS_NUM_TIERS_VAG
      ,DAS.DEC_DATE_CREATION
      ,DAS.DEC_DATE_MAJ
      ,DAS.DEC_DATE_MAJ_TEC
      ,DAS.dec_typ_declinaison
      ,row_number() over (partition by DAS.ELG_NUM_ELT_GESTION_ELG ORDER BY DAS.ELG_NUM_ELT_GESTION_ELG) as DASRN
      FROM
          MDS_DECLINAISON_ARTICLE DAS
      ) DAS3
  LEFT OUTER JOIN (
        SELECT
          DAS1.*,row_number() over (partition by DAS1.ELG_NUM_ELT_GESTION_ELG ORDER BY DAS1.ELG_NUM_ELT_GESTION_ELG) as DASRN2
        FROM
          MDS_DECLINAISON_ARTICLE DAS1) DAS2
  ON
            DAS3.ELG_NUM_ELT_GESTION_ELG = DAS2.ELG_NUM_ELT_GESTION_ELG
        AND DAS3.TTI_NUM_TYPE_TIERS_VAG = DAS2.TTI_NUM_TYPE_TIERS_VAG
        AND DAS3.TIR_NUM_TIERS_VAG = DAS2.TIR_NUM_TIERS_VAG
        AND DAS3.TIR_SOUS_NUM_TIERS_VAG = DAS2.TIR_SOUS_NUM_TIERS_VAG
        AND DAS3.DEC_TYP_DECLINAISON = DAS2.DEC_TYP_DECLINAISON
        AND DAS3.DASRN != DAS2.DASRN2
  WHERE
        DAS3.TTI_NUM_TYPE_TIERS_VAG = 15
    AND DAS3.TIR_NUM_TIERS_VAG = 0
    AND DAS3.TIR_SOUS_NUM_TIERS_VAG = 0
  AND  DAS3.DEC_TYP_DECLINAISON <> '1'
) DA
ON
  DA.ELG_NUM_ELT_GESTION_ELG = EG.ELG_NUM_ELT_GESTION_ELG
---------------------------------------------------------------------------
LEFT OUTER JOIN
  MDS_VAL_GRILLE VG
ON
    VG.TGR_NUM_TYPE_GRILLE_GRL = DA.TGR_NUM_TYPE_GRILLE_VAG
AND VG.VAL_GRILLE_VAG = DA.VAL_GRILLE_VAG
AND VG.TTI_NUM_TYPE_TIERS_GRL = DA.TTI_NUM_TYPE_TIERS_VAG
AND VG.TIR_NUM_TIERS_GRL = DA.TIR_NUM_TIERS_VAG
AND VG.TIR_SOUS_NUM_TIERS_GRL = DA.TIR_SOUS_NUM_TIERS_VAG
---------------------------------------------------------------------------
INNER JOIN
  MDS_RATTACHEMENT_MODELE RM
ON
    RM.ELG_NUM_ELT_GESTION_ELG = EG.ELG_NUM_ELT_GESTION_MOD
AND (RM.ORG_NUM_ORGANISATION_ELN = 1 OR RM.ORG_NUM_ORGANISATION_ELN = 2 OR RM.ORG_NUM_ORGANISATION_ELN = 3 OR RM.ORG_NUM_ORGANISATION_ELN = 4 )
---------------------------------------------------------------------------
LEFT OUTER JOIN
  MDS_ELT_NIVEAU ELNFAM
ON
    RM.ORG_NUM_ORGANISATION_ELN = ELNFAM.ORG_NUM_ORGANISATION_NIV
AND RM.NIV_NUM_NIVEAU_ELN = ELNFAM.NIV_NUM_NIVEAU_NIV
AND RM.ELN_NUM_ELT_NIVEAU_ELN = ELNFAM.ELN_NUM_ELT_NIVEAU
---------------------------------------------------------------------------
LEFT OUTER JOIN
  MDS_ELT_NIVEAU ELNSSR
ON
    ELNSSR.ORG_NUM_ORGANISATION_NIV = ELNFAM.ORG_NUM_ORGANISATION_SUP
AND ELNSSR.NIV_NUM_NIVEAU_NIV = ELNFAM.NIV_NUM_NIVEAU_SUP
AND ELNSSR.ELN_NUM_ELT_NIVEAU = ELNFAM.ELN_NUM_ELT_NIVEAU_SUP
---------------------------------------------------------------------------
LEFT OUTER JOIN
  MDS_ELT_NIVEAU ELNRAY
ON
    ELNRAY.ORG_NUM_ORGANISATION_NIV = ELNSSR.ORG_NUM_ORGANISATION_SUP
AND ELNRAY.NIV_NUM_NIVEAU_NIV = ELNSSR.NIV_NUM_NIVEAU_SUP
AND ELNRAY.ELN_NUM_ELT_NIVEAU = ELNSSR.ELN_NUM_ELT_NIVEAU_SUP
---------------------------------------------------------------------------
LEFT OUTER JOIN
  MDS_ELT_NIVEAU ELNUNI
ON
    ELNUNI.ORG_NUM_ORGANISATION_NIV = ELNRAY.ORG_NUM_ORGANISATION_SUP
AND ELNUNI.NIV_NUM_NIVEAU_NIV = ELNRAY.NIV_NUM_NIVEAU_SUP
AND ELNUNI.ELN_NUM_ELT_NIVEAU = ELNRAY.ELN_NUM_ELT_NIVEAU_SUP
---------------------------------------------------------------------------
LEFT OUTER JOIN
  MDS_ELT_NIVEAU ELNMAG
ON
    ELNMAG.ORG_NUM_ORGANISATION_NIV = ELNUNI.ORG_NUM_ORGANISATION_SUP
AND ELNMAG.NIV_NUM_NIVEAU_NIV = ELNUNI.NIV_NUM_NIVEAU_SUP
AND ELNMAG.ELN_NUM_ELT_NIVEAU = ELNUNI.ELN_NUM_ELT_NIVEAU_SUP
---------------------------------------------------------------------------
LEFT JOIN
  MDS_LIBELLE_TRADUCTION MLT1
ON
  LM.LIB_NUM_LIBELLE_LIB = MLT1.LIB_NUM_LIBELLE_LIB
---------------------------------------------------------------------------
LEFT JOIN
  MDS_LIBELLE_TRADUCTION MLT2
ON
  ELNFAM.LIB_NUM_LIBELLE_LIB = MLT2.LIB_NUM_LIBELLE_LIB
---------------------------------------------------------------------------
LEFT JOIN
  MDS_LIBELLE_TRADUCTION MLT3
ON
  ELNSSR.LIB_NUM_LIBELLE_LIB = MLT3.LIB_NUM_LIBELLE_LIB
---------------------------------------------------------------------------
LEFT JOIN
  MDS_LIBELLE_TRADUCTION MLT4
ON
  ELNRAY.LIB_NUM_LIBELLE_LIB = MLT4.LIB_NUM_LIBELLE_LIB
---------------------------------------------------------------------------
LEFT JOIN
  MDS_LIBELLE_TRADUCTION MLT5
ON
  ELNUNI.LIB_NUM_LIBELLE_LIB = MLT5.LIB_NUM_LIBELLE_LIB
---------------------------------------------------------------------------
WHERE
    MLT1.TLB_TYP_LIBELLE_LIB = 'LMO'
AND MLT1.LAN_CODE_LANGUE_LAN = 'EN'
AND MLT2.TLB_TYP_LIBELLE_LIB = 'ELN'
AND MLT2.LAN_CODE_LANGUE_LAN = 'EN'
AND MLT3.TLB_TYP_LIBELLE_LIB = 'ELN'
AND MLT3.LAN_CODE_LANGUE_LAN = 'EN'
AND MLT4.TLB_TYP_LIBELLE_LIB = 'ELN'
AND MLT4.LAN_CODE_LANGUE_LAN = 'EN'
AND MLT5.TLB_TYP_LIBELLE_LIB = 'ELN'
AND MLT5.LAN_CODE_LANGUE_LAN = 'EN'
AND EG.ELG_MOD_OU_ART = '0'
AND CAST(CF1.COF_CODE_FOURNISSEUR AS INT) IS NOT NULL
AND CAST(CF2.COF_CODE_FOURNISSEUR AS INT) IS NOT NULL
AND LM.LIB_NUM_LIBELLE_LIB IS NOT NULL
AND ELNFAM.LIB_NUM_LIBELLE_LIB IS NOT NULL
AND ELNSSR.LIB_NUM_LIBELLE_LIB IS NOT NULL
AND ELNRAY.LIB_NUM_LIBELLE_LIB IS NOT NULL
AND ELNUNI.LIB_NUM_LIBELLE_LIB IS NOT NULL
AND ELNMAG.LIB_NUM_LIBELLE_LIB IS NOT NULL""")

tableFinale.repartition(80).write.option("compression", "snappy").mode("overwrite").format("parquet").saveAsTable(
    "kylin_usb_mqb.flat_structure")
